name: rick_and_morty_app
description: "Risk and morty API app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  go_router: ^14.8.0
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  change_app_package_name: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/

flutter_launcher_icons:
      android: "launcher_icon"
      ios: true
      remove_alpha_ios: true
      image_path: "assets/images/icon.png"
      min_sdk_android: 24 
      adaptive_icon_background: "#4A4A4C" 
      adaptive_icon_foreground: "assets/images/icon.png" 

flutter_native_splash:
  color: "#010101"
  image: assets/images/icon.png
  android_12: 
    image: assets/images/icon.png
    color: "#010101"
